[package]
name = "kimuti-package-manager"
version = "0.1.0"
edition = "2021"
default-run = "kimuti"

[[bin]]
name = "kimuti"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
